Initial Services
openforis/arena-server pull request #33
Opened 2021-04-22 10:46 UTC by sorja

## Description
Added initial services

- #### Added/Removed/Updated something...

- SurveyService.get
- RecordService.get
- UserService.get
- UserResetPasswordRepository.hasValidResetPassword
- AuthGroupRepository.fetchUserGroups ==> AuthGroupRepository.getMany({userUuid})

- Added also .join().on()

## Types of changes

- [ ] Docs change
- [ ] Refactoring
- [ ] Dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How has this been tested

#### Do you consider this PR needs further testing?

- [x] No
- [ ] Yes

## Disclaimer

- [ ] Todo: Add dbTransformCallback to some queries

2021-04-22 10:46 UTC, minotogna commented
Task linked: [CU-hf7c13 Initial services](https://app.clickup.com/t/hf7c13)

2021-04-22 16:54 UTC, minotogna commented on src/db/dbs/transformCallback.ts
> +  rowUpdated.propsDraft = row.props_draft
what if the returned object doesn't need to include the propsDraft property?

2021-04-22 16:59 UTC, minotogna commented on src/db/sql/sqlSelectBuilder.ts
> +    }
if we have several joins, won't this produce something like (where o is the source table):
```sql
join schema.tableA as a schema.tableB as b ON
o.a = a.a o.b = b.b 
```
would't we need to have a JoinConditionBuilder?

2021-04-23 07:01 UTC, SteRiccio approved these changes

2021-04-23 07:36 UTC, minotogna requested changes

2021-04-23 07:36 UTC, minotogna commented on src/db/sql/sqlJoinBuilder.ts
> +}
this is single join. SqlSelectBuilder has an array of sqlJoinBuilders

2021-04-23 08:41 UTC, minotogna submitted a review, later dismissed

2021-04-23 13:19 UTC, minotogna approved these changes

2021-04-23 13:57 UTC, SteRiccio approved these changes

2021-04-23 13:58 UTC, merged